# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: blog.aidengrong.top
    url: https://blog.aidengrong.top
  - name: pan.aidengrong.top
    url: https://pan.aidengrong.top
  - name: chat.aidengrong.top
    url: https://chat.aidengrong.top
  - name: chat2.aidengrong.top
    url: https://chat2.aidengrong.top
  - name: chat3.aidengrong.top
    url: https://chat3.aidengrong.top
  - name: chat4.aidengrong.top
    url: https://chat4.aidengrong.top
  - name: img.aidengrong.top
    url: https://img.aidengrong.top
  - name: web.aidengrong.top
    url: https://web.aidengrong.top
  - name: analytics.aidengrong.top
    url: https://analytics.aidengrong.top
  - name: wallpaper.aidengrong.top
    url: https://wallpaper.aidengrong.top
  - name: qiandao.aidengrong.top
    url: https://qiandao.aidengrong.top
  - name: a.aidengrong.top
    url: https://a.aidengrong.top
  - name: b.aidengrong.top
    url: https://b.aidengrong.top
  - name: glitch搭建的xray
    url: https://tinted-jolly-headstand.glitch.me/list
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
